-- Commerce Schema Foundation (Cart & Wishlist)

CREATE TABLE IF NOT EXISTS Carts (
    Id UUID PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE UNIQUE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CartItems (
    Id SERIAL PRIMARY KEY,
    CartId UUID REFERENCES Carts(Id) ON DELETE CASCADE,
    ProductId UUID REFERENCES Products(Id) ON DELETE CASCADE,
    VariantId INT,
    Quantity INT NOT NULL DEFAULT 1 CHECK (Quantity > 0),
    UNIQUE(CartId, ProductId)
);

CREATE TABLE IF NOT EXISTS Wishlists (
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    ProductId UUID REFERENCES Products(Id) ON DELETE CASCADE,
    AddedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserId, ProductId)
);
