-- Account Additions

ALTER TABLE Users ADD COLUMN IF NOT EXISTS AvatarUrl TEXT;
ALTER TABLE Users ADD COLUMN IF NOT EXISTS MemberTier VARCHAR(50) DEFAULT 'Standard';

CREATE TABLE IF NOT EXISTS UserWarranties (
    Id SERIAL PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    ProductId UUID REFERENCES Products(Id) ON DELETE CASCADE,
    SerialNumber VARCHAR(100),
    Status VARCHAR(50) DEFAULT 'Active', -- Active, Expired
    ExpiryDate TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS UserCoupons (
    Id SERIAL PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    Code VARCHAR(50) UNIQUE NOT NULL,
    DiscountPercentage DECIMAL(5,2),
    Status VARCHAR(50) DEFAULT 'Available', -- Available, Used, Expired
    ExpiryDate TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS UserComplaints (
    Id SERIAL PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    TicketNumber VARCHAR(50) UNIQUE NOT NULL,
    Subject VARCHAR(255) NOT NULL,
    Status VARCHAR(50) DEFAULT 'Open', -- Open, Resolved
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UserRewards (
    Id SERIAL PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    Points INT NOT NULL,
    Reason VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UserNotifications (
    Id SERIAL PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    Title VARCHAR(255) NOT NULL,
    Message TEXT NOT NULL,
    IsRead BOOLEAN DEFAULT FALSE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UserSettings (
    UserId UUID PRIMARY KEY REFERENCES Users(Id) ON DELETE CASCADE,
    EmailNotifications BOOLEAN DEFAULT TRUE,
    SmsNotifications BOOLEAN DEFAULT TRUE,
    PushNotifications BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS SavedPaymentMethods (
    Id SERIAL PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE,
    Provider VARCHAR(50) NOT NULL, -- Visa, MasterCard, UPI
    Last4 VARCHAR(4),
    ExpiryMonth INT,
    ExpiryYear INT,
    IsDefault BOOLEAN DEFAULT FALSE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
