ALTER TABLE Products ADD COLUMN IF NOT EXISTS ReservedStock INT DEFAULT 0;
ALTER TABLE Products ADD COLUMN IF NOT EXISTS SoldStock INT DEFAULT 0;

ALTER TABLE Coupons ADD COLUMN IF NOT EXISTS AssignedToEmail VARCHAR(255) NULL;
ALTER TABLE Coupons ADD COLUMN IF NOT EXISTS UsageLimit INT DEFAULT NULL;
ALTER TABLE Coupons ADD COLUMN IF NOT EXISTS TimesUsed INT DEFAULT 0;
