-- 129_FlashSales.sql
ALTER TABLE FlashSales ADD COLUMN IF NOT EXISTS DiscountValue DECIMAL(10,2) DEFAULT 0;
ALTER TABLE FlashSales ADD COLUMN IF NOT EXISTS TargetType VARCHAR(50) DEFAULT 'Product'; -- 'Product' or 'Category'
ALTER TABLE FlashSales ADD COLUMN IF NOT EXISTS TargetCategoryId INT NULL;
