ALTER TABLE CatalogPromotions ADD COLUMN IF NOT EXISTS SpecificProducts JSONB;
ALTER TABLE FlashSales ADD COLUMN IF NOT EXISTS TargetBrandId INT NULL REFERENCES Brands(Id);
ALTER TABLE FlashSales ADD COLUMN IF NOT EXISTS SpecificProducts JSONB;
